server:
  port: 8088

logging:
  level:
    org.springframework: DEBUG

spring:
  messages:
    basename: messages
    encoding: UTF-8
#  security:
#    user:
#      name: username
#      password: pass0rd
  jpa:
    show-sql: true
  h2:
    console:
      enabled: true

  datasource:
    url: jdbc:h2:mem:testdb

management:
  endpoints:
    web:
      exposure:
        include: "*"







